import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import CircularCursor from "@/components/CircularCursor ";

const body = localFont({
  src: "./fonts/CinzelDecorative-Regular.ttf",
  variable: "--font-Ruquaa",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Mythology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${body.className} antialiased text-white bg-black `}>
        <CircularCursor />
        {children}
      </body>
    </html>
  );
}
